source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "webrick", "~> 1.8"
gem "sass", "~> 3.7"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end 